api-version : 1.16
main: fr.stormer3428.TPA.Tpa
author: stormer3428
name: "StormerTPA"
api : []
version: 0.0.6
commands:
  tpa:
    description: "Sends a request to teleport you to a player"
  tpahere:
    description: "Sends a request to teleport a player to you"
    aliases: [tpah]
  tpaccept:
    description: "Accepts the teleport request"
    aliases: [tpyes]
  tpdeny:
    description: "Refuses the teleport request"
    aliases: [tpno]